name: Pre-Checks

on:
  workflow_call:
    inputs:
      flutter_version:
        required: false
        type: string
        default: "stable"

jobs:
  dart-format:
    name: Dart Format
    runs-on: ubuntu-24.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          sdk: ${{ inputs.flutter_version }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Dart Format
        run: dart format --set-exit-if-changed .

  dart-analyze:
    name: Dart Analyze
    runs-on: ubuntu-24.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          sdk: ${{ inputs.flutter_version }}

      - name: Install Dependencies
        run: flutter pub get

      - name: Dart Analyze
        run: dart analyze --fatal-warnings
